### ISSUE TITLE
Report with done "comment"

### ISSUE THREAD

**Issue by markedphillips** [mrcook/time_warrior#1]
Is there a plan to output project report tasks with the comment which was posted on the done command?

**Comment by mrcook** [comment]
Hi Mark, I have no clue how this happened, but I completely missed your comment until now...I'm super sorry about that.

This is actually a good idea. I'll have a think how this might work, and how to integrate the current tasks details into that report. If I can come up with something reasonable I'll certainly add the feature.

Many thanks,
Michael

**Comment by mrcook** [comment]
Hi Mark, after giving this some thought I've decided against adding this feature. The idea is still good, but unfortunately the applicatin design doesn't lend itself easily to this change.

The only reasonable display I can think of would be this:

`Test.Done | Started: 2020-02-22 15:18 | Worked: 15 seconds | Task Total: 5m | Status: completed`

However, the timeslip and reporting code are completely separated, so I'd need to redesign a lot of the application to make this work.

As it's easy and fast to get a report: `tw report Test` I think it's an acceptable burden on the user.

Many thanks for your suggestion,
Michael
