### ISSUE TITLE
Enhancement: Add a status command

### ISSUE THREAD

**Issue by carbontwelve** [mrcook/time_warrior#2]
I absolutely love the simplicity of this tool and have been using it for the past two weeks to log time against tasks to help improve my future ETA estimates.

I often find myself coming back to my computer in the morning and wanting to know the status of `tw`; essentially do I have a paused timeslip from the previous day?

My suggestion is the addition of a `status` command that simply checks if there is a paused/in-progress timeslip and outputs its status. If there isn't a paused/in-progress time slip it responds with something like "No current timeslip".

## Edit:

> By default, running the application will display the help page, however, if you have a pending timeslip in progress then those details will be printed instead

I just re-read the README and notice this functionality is what happens when you run `tw` with a pending timeslip in progress. I guess that makes this feature request void?

**Comment by mrcook** [comment]
Hi Simon, I'm really sorry for not answering sooner -- I don't know how this passed me by.

As you say, just typing `tw` will show you the pending status if one exists. I think you are right that this suggestion can be closed.

It's great to hear you're finding tw useful. Like you, I use it to help in estimations, but it's also nice - and sometimes scary - to know how much time I put into my hobby projects!
