### ISSUE TITLE
Bug: Running pause command without an open timeslip

### ISSUE THREAD

**Issue by carbontwelve** [mrcook/time_warrior#3]
## Steps to reproduce

Run `tw pause` without having first started a timeslip.

## Expected Behaviour

The tool informs the user that they do not currently have an open timeslip.

## Actual Behaviour

```bash
$ tw pause
unexpected end of JSON input
```

**Comment by mrcook** [comment]
Thanks for the bug report Simon, this is now fixed with https://github.com/mrcook/time_warrior/commit/76abaaf8cf00988b44d46cdcb5c629e26c218a5a.
